### ISSUE TITLE
Fehler in getCookiefile/setCookiefile

### ISSUE THREAD

**Issue by asdfklgash** [inwx/php-client#1]
Es wird fälschlicherweise auf `$this->$_cookiefile` zugegriffen, richtig müsste es aber `$this->_cookiefile` (also ohne `$`) heißen.

**Comment by kekskurse** [comment]
Vielen Dank für den Hinweis, die Änderungen sind im Masterbranch erfolgt und werden auch in die nächste Version einfließen.
