### ISSUE TITLE
composer installation fails

### ISSUE THREAD

**Issue by daslicht** [inwx/php-client#2]
Hi,
What is going wrong please:

```
daslicht:steps daslicht$ composer require inwx/domrobot

  [InvalidArgumentException]                                                   
  Could not find package inwx/domrobot at any version for your minimum-stabil  
  ity (stable). Check the package spelling or your minimum-stability           




```

**Comment by kekskurse** [comment]
Hello, thanks for your report. 

As fast solution you can add a `minimum-stability` Flag to your composer.json. There is a Documentation-Page from composer about this topic https://getcomposer.org/doc/04-schema.md#minimum-stability

For Example

```
{
    "minimum-stability":"dev",
    "require":
    {
        "inwx/domrobot":"dev-master"
    }
}
```

as composer.json works on my machine.

**Comment by kekskurse** [comment]
The installation via composer  with the `composer require inwx/domrobot` command works now.

**Comment by daslicht** [comment]
Yeah indeed , thank you.
Do I need anything else ? `require` , `use`
It is added to teh autolad automatically no ?

**Comment by daslicht** [comment]
I tried : 

```
use INWX\Domrobot;
```

```
 $robot = new Domrobot();
```

result:

```
Class 'INWX\Domrobot' not found
```

see: https://github.com/JumpLinkNetwork/steps/blob/master/Plugin.php#L7

**Comment by kekskurse** [comment]
If you run `composer require inwx/domrobot` it should create a line `"inwx/domrobot": "^2.4"` in the required path of the composer.json. In your project this is the dev-master branch which also should be ok. 

Did some messages appear when you run `composer update`? Can you please add a test php file in the root folder of the Project and add the following code:

```
<?php
include("vendor/autoload.php");
use INWX\Domrobot;
$domrobot = new  Domrobot($addr);
var_dump($domrobot);
```

if the result starts with  `object(INWX\Domrobot)` the composer installation is ok. In the code also in line 108 a `new` is missing before Domrobot().

**Comment by daslicht** [comment]
```
If you run composer require inwx/domrobot it should create a line "inwx/domrobot": "^2.4" in the required path of the composer.json. In your project this is the dev-master branch which also should be ok.
```

Thats works.

```
Did some messages appear when you run composer update? 
```

just fine 

unfortunately I can't call my created test.php for some reason : 

```
http://octobercms.site/plugins/jumplink/steps/test.php
```

Maybe octobercms intercepting it somehow

**Comment by daslicht** [comment]
I managed to get it working, deeper in the Plugin Hirachy.
Looks like the Plugin.php is the wrong place to use vendor libs

**Comment by daslicht** [comment]
still broken :(

**Comment by daslicht** [comment]
Looks like its finding the Class now but I get :

```
Call to undefined function INWX\xmlrpc_encode_request()
/Applications/AMPPS/www/october/plugins/jumplink/steps/vendor/inwx/domrobot/INWX/Domrobot.php line 100
```

[edit]
trying to install xmlrpc_encode_request

**Comment by kekskurse** [comment]
On ubuntu or general debian based systems you can install it via apt-get
`sudo apt-get install php5-xmlrpc`

http://php.net/manual/de/xmlrpc.installation.php

**Comment by daslicht** [comment]
I am trying it locally on OSX.

Meanwhile Ive successfully got it running using aamps which included the compiled extension.

```
            $addr = "https://api.ote.domrobot.com/xmlrpc/";
            $domrobot = new Domrobot($addr);
            var_dump($domrobot);
```

returns:

```
object(INWX\Domrobot)#591 (7) { ["debug":"INWX\Domrobot":private]=> bool(false) ["address":"INWX\Domrobot":private]=> string(36) "https://api.ote.domrobot.com/xmlrpc/" ["language":"INWX\Domrobot":private]=> NULL ["customer":"INWX\Domrobot":private]=> bool(false) ["clTRID":"INWX\Domrobot":private]=> NULL ["_ver":"INWX\Domrobot":private]=> string(3) "2.4" ["_cookiefile":"INWX\Domrobot":private]=> string(67) "/private/var/folders/1g/2mhrk9qs52d8dr73f94qdngw0000gn/T/INWx1dhcNq" }
```

is that ok  ?

[EDIT]

SUCCESS!

**Comment by daslicht** [comment]
@sspssp is there also php7-xmlrpc ?

**Comment by kekskurse** [comment]
There is a Package for Debian/Ubuntu Server
http://packages.ubuntu.com/search?suite=xenial&section=all&arch=any&keywords=php7.0-xmlrpc&searchon=names
https://packages.debian.org/search?searchon=names&keywords=php7.0-xmlrpc
