### ISSUE TITLE
Fatal error Declaration of $logger must be compatible 

### ISSUE THREAD

**Issue by natsandbox** [inwx/php-client#22]
Using PHP 8.1 we get the following error when using the example code: 

Fatal error: Declaration of INWX\Domrobot::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void in

**Comment by ddmler** [comment]
We have released v3.4.0 which fixes this error. Please use this new version.
