### ISSUE TITLE
Require error

### ISSUE THREAD

**Issue by daslicht** [inwx/php-client#3]
Hi, 
when I manually require the Domrobot.php file I get :

```
FatalErrorException in Plugin.php line 93:
main(): Failed opening required './vendor/php-client/INWX/Domrobot.php' (include_path='.:/Applications/MAMP/bin/php/php5.6.10/lib/php')
```

?

**Comment by kekskurse** [comment]
When you download the domrobot manually it's better to put the file into a seperate directory, not the vendor directory. The vendor directory is only used by composer and should not be edited manually. If you use composer to load the API-Client, you don't need to require the file, it will be installed with the composer autoloader.
Make sure the file exists in the given path (e.g. use http://php.net/manual/de/function.file-exists.php to test it inside the php script). 

If you clone the project inside a directory

```
git clone git@github.com:inwx/php-client.git
```

you can use the following command to include the file

```
require("php-client/INWX/Domrobot.php");
```

To test if the file exists in this case, the following code will show:

```
if(file_exists("php-client/INWX/Domrobot.php"))
{
echo "ok";
}
else
{
echo "File not Exists";
}
```

If the message is "File not Exists" appears, double check the path to the Domrobot.php
