### ISSUE TITLE
No autoload file

### ISSUE THREAD

**Issue by TheKenzo** [inwx/php-client#7]
I get vendor/autoload.php file error: not found

PHP library

I want to run this on a shared hosting (because i'm the owner of a billing software and i want to integrate with it, i want to make installation simple, without composer, just upload addon[module / plugin] in my billing software (and on install of addon, to request username and password [system already done], after install the system should work))

On GitHub files i don't find any vendor/autoload.php

**Comment by ddmler** [comment]
You have to use `composer install` to get the vendor/autoload.php file. However if you want to use it like you described, you can use composer install once and afterward copy the complete vendor folder to your addon.

Just remember that you won't get any updates this way, so you have to update manually from time to time.
