### ISSUE TITLE
Consider PSR-3 LoggerAwareInterface?

### ISSUE THREAD

**Issue by christoph-kluge** [inwx/php-client#8]
Currently I'm implementing this client and when setting `debug` to `true` then the request and response's are directly `echo`'ed. During development this might be handy but I guess there might be other people like me who would have more control over when and where the logs should appear. Especially if you want to log things in other environments rather than your local development machine.

Did you considered adding compatibility with PSR-3 `LoggerAwareInterface` so people could handle this on their own?

**Comment by ddmler** [comment]
Hey, thanks for your suggestion, we have released a new version which implements the LoggerAwareInterface. Please check it out and let us know if you need any help with our client.

**Comment by christoph-kluge** [comment]
@ddmler thank you very much! Small side note to the code: The PSR also gives a `LoggerAwareTrait` which fulfils the `LoggerAwareInterface` and contains the `setLogger()` member function. 

Anyway I'll be publishing soon my INWX client extension. It's a wrapper around this low-level client which will give code completion for all my use-cases. 

Are you interessted to put it somewhere as soon as I publish it?

**Comment by ddmler** [comment]
Yes, just let us know when you're done and we will gladly take a look at it.
